theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
true-color = true
bufferline = "multiple"
scrolloff = 8
rulers = [120]
completion-trigger-len = 1
end-of-line-diagnostics = "hint"

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 3000

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "disable"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true
snippets = true

[editor.indent-guides]
render = true
character = "╎"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "file-modification-indicator"]
center = ["diagnostics"]
right = ["selections", "register", "position", "file-encoding", "file-line-ending", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
"C-s" = ":write"

[keys.insert]
"j" = { "k" = "normal_mode" }
